In [2]:
import numpy as np
from cs682.gradient_check import eval_numerical_gradient_array

def dnum(f,x):
    return eval_numerical_gradient_array(f,x,1,h=1e-6)

def asum(x):
    return np.sum(x,axis=0)*np.ones_like(x)

def dasum(x):
    return 1

def x_asum(x):
    return x*(asum(x))

def dx_asum(x):
    return asum(x)+x*dasum(x)

a = np.array([[441, 2,3,234], [15, 4,5,45],[2,3,4,12]],dtype=float)
f = lambda inp: x_asum(inp)
print("numerical\n",dnum(f,a))
print("analytical\n",dx_asum(a))
print("*"*60)


numerical
 [[916.00000565  18.00000001  24.00000001 581.99999648]
 [916.00001065  18.00000001  24.00000002 582.00000558]
 [916.0000107   18.00000001  24.00000001 582.00000694]]
analytical
 [[899.  11.  15. 525.]
 [473.  13.  17. 336.]
 [460.  12.  16. 303.]]
************************************************************


In [ ]:
import numpy as np
from cs682.gradient_check import eval_numerical_gradient_array



def gbx(x,eps):
    return (np.mean(x, axis=0))/np.sqrt(np.var(x,axis=0)+eps)

def dgbx(x,eps):
    n = x.shape[0]
    mu = np.mean(x, axis=0)
    sqrtvarf = np.sqrt(np.var(x,axis=0)+eps)
    a = x - np.mean(x, axis=0)
    return (1/(n*sqrtvarf))-(mu*dfvarf(x,eps))/(sqrtvarf**2)


def gx(x,eps):
    return (x - np.mean(x, axis=0))/np.sqrt(np.var(x,axis=0)+eps)

def dgx(x,eps):
    return dgax(x,eps) - dgbx(x,eps)
    n = x.shape[0]
    mu = np.mean(x, axis=0)
    a = x - np.mean(x, axis=0)
    varf = np.sqrt(np.var(x,axis=0)+eps)
    xc = a/varff
    return (1/(varf*n))(1-((mu*xc)/varf))
    return xc/n

def jx(x):
    return 1/x

def djx(x):
    return -1/x**2

import numpy as np
from cs682.gradient_check import eval_numerical_gradient_array


def fvarf(x,eps):
    return np.var(x,axis=0)+eps#np.sum((x-mu)**2,axis=0)/n

def fvarf_sqrt(x,eps):
    return np.sqrt(fvarf(x,eps))

def dfvarf(x,eps):
    n = x.shape[0]
    mu = np.mean(x, axis=0)
    #sqrtvarf = np.sqrt(np.var(x,axis=0)+eps)
    return (2*(x-mu)/n)#/(fvarf(x,eps)**2)

def fvarf_sqrt(x,eps):
    return np.sqrt(fvarf(x,eps))

def dfvarf_sqrt(x,eps):
    n=x.shape[0]
    return (1/np.sqrt(np.var(x,axis=0)+eps))*(x-np.mean(x, axis=0))/n

def fvarf_sqrt_inv(x,eps):
    return np.sum(x,axis=0)
    return 1/np.sqrt(np.var(x,axis=0))

def dfvarf_sqrt_inv(x,eps):
    return np.ones_like(x)
    return (-1./(np.var(x,axis=0)))*dfvarf_sqrt(x,eps)

def gax(x,eps):
    #print ("X: \n",x)
    #print("fvarf_sqrt_inv: \n",fvarf_sqrt_inv(x,eps))
    #print ("X*fvarf_sqrt_inv: \n",x*fvarf_sqrt_inv(x,eps))
    return x*fvarf_sqrt_inv(x,eps)

def dgax(x,eps):
    return np.ones_like(x)*fvarf_sqrt_inv(x,eps)+(dfvarf_sqrt_inv(x,eps)*x)

def dnum(f,x):
    return eval_numerical_gradient_array(f,x,1,h=1e-6)

eps = 0#1e-5

a = np.array([[441, 2,3,234], [15, 4,5,45],[2,3,4,12]],dtype=float)

print(a*(1/(a*a)),"\n",1/a)
#a = np.array([[12,3],[1,2]],dtype=float)

f = lambda inp: fvarf_sqrt_inv(inp,eps)
print("numerical\n",dnum(f,a))
print("analytical\n",dfvarf_sqrt_inv(a,eps))
print("*"*60)

f = lambda inp: gax(inp,eps)
print("numerical\n",dnum(f,a))
print("analytical\n",dgax(a,eps))


def 

In [ ]:
import numpy as np
from cs682.gradient_check import eval_numerical_gradient_array

def dnum(f,x):
    return eval_numerical_gradient_array(f,x,1,h=1e-6)

def asum(x):
    return np.sum(x,axis=0)*np.ones_like(x)

def dasum(x):
    return 1

def x_asum(x):
    return x*(asum(x))

def dx_asum(x):
    return asum(x)+x*dasum(x)


f = lambda inp: x_asum(inp)
print("numerical\n",dnum(f,a))
print("analytical\n",dx_asum(a))
print("*"*60)
