In [7]:
import numpy as np
d = np.arange(1,41,1).reshape(5,4,2)
k=np.prod(d.shape[1:])
d=d.reshape(d.shape[0],k)
print(d-1,d)

s=[2]+[2,3,55]+[3]
for i in range(1,len(s)):
    print(s[i])
print(np.sqrt(100))
w=0.99
print(w**2)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]] [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]]
2
3
55
3
10.0
0.9801
