In [7]:
import numpy as np
a=np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]])
b=np.array([[1,2],[3,4]])
print(a.transpose(1,0,2,3))
print(b*c)
print((1,2)+(3,4))


[[[[ 1  2]
   [ 3  4]]

  [[ 9 10]
   [11 12]]]


 [[[ 5  6]
   [ 7  8]]

  [[13 14]
   [15 16]]]]
[[2 4]
 [6 8]]
(1, 2, 3, 4)


In [4]:
import numpy as np
from cs682.gradient_check import eval_numerical_gradient_array
a=np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]],dtype=float)
print(a.shape)
'''
dana=np.ones_like(a)
f = lambda xx: xx
danum=eval_numerical_gradient_array(f,a,1)
print(eval_numerical_gradient_array(f,np.array([[1,2],[3,4]],dtype=float),1))
print(5 * np.random.randn(2,2,2,2) + 12)
print(danum,"\n")
print(dana,"\n")
'''

(2, 2, 2, 2)


'\ndana=np.ones_like(a)\nf = lambda xx: xx\ndanum=eval_numerical_gradient_array(f,a,1)\nprint(eval_numerical_gradient_array(f,np.array([[1,2],[3,4]],dtype=float),1))\nprint(5 * np.random.randn(2,2,2,2) + 12)\nprint(danum,"\n")\nprint(dana,"\n")\n'

In [ ]:
import numpy as np
from cs682.gradient_check import eval_numerical_gradient_array



def gbx(x,eps):
    return (np.mean(x, axis=0))/np.sqrt(np.var(x,axis=0)+eps)

def dgbx(x,eps):
    n = x.shape[0]
    mu = np.mean(x, axis=0)
    sqrtvarf = np.sqrt(np.var(x,axis=0)+eps)
    a = x - np.mean(x, axis=0)
    return (1/(n*sqrtvarf))-(mu*dfvarf(x,eps))/(sqrtvarf**2)


def gx(x,eps):
    return (x - np.mean(x, axis=0))/np.sqrt(np.var(x,axis=0)+eps)

def dgx(x,eps):
    return dgax(x,eps) - dgbx(x,eps)
    n = x.shape[0]
    mu = np.mean(x, axis=0)
    a = x - np.mean(x, axis=0)
    varf = np.sqrt(np.var(x,axis=0)+eps)
    xc = a/varff
    return (1/(varf*n))(1-((mu*xc)/varf))
    return xc/n

def jx(x):
    return 1/x

def djx(x):
    return -1/x**2

import numpy as np
from cs682.gradient_check import eval_numerical_gradient_array


def fvarf(x,eps):
    return np.var(x,axis=0)+eps#np.sum((x-mu)**2,axis=0)/n

def fvarf_sqrt(x,eps):
    return np.sqrt(fvarf(x,eps))

def dfvarf(x,eps):
    n = x.shape[0]
    mu = np.mean(x, axis=0)
    #sqrtvarf = np.sqrt(np.var(x,axis=0)+eps)
    return (2*(x-mu)/n)#/(fvarf(x,eps)**2)

def fvarf_sqrt(x,eps):
    return np.sqrt(fvarf(x,eps))

def dfvarf_sqrt(x,eps):
    n=x.shape[0]
    return (1/np.sqrt(np.var(x,axis=0)+eps))*(x-np.mean(x, axis=0))/n

def fvarf_sqrt_inv(x,eps):
    return np.sum(x,axis=0)
    return 1/np.sqrt(np.var(x,axis=0))

def dfvarf_sqrt_inv(x,eps):
    return np.ones_like(x)
    return (-1./(np.var(x,axis=0)))*dfvarf_sqrt(x,eps)

def gax(x,eps):
    #print ("X: \n",x)
    #print("fvarf_sqrt_inv: \n",fvarf_sqrt_inv(x,eps))
    #print ("X*fvarf_sqrt_inv: \n",x*fvarf_sqrt_inv(x,eps))
    return x*fvarf_sqrt_inv(x,eps)

def dgax(x,eps):
    return np.ones_like(x)*fvarf_sqrt_inv(x,eps)+(dfvarf_sqrt_inv(x,eps)*x)

def dnum(f,x):
    return eval_numerical_gradient_array(f,x,1,h=1e-6)

eps = 0#1e-5

a = np.array([[441, 2,3,234], [15, 4,5,45],[2,3,4,12]],dtype=float)

print(a*(1/(a*a)),"\n",1/a)
#a = np.array([[12,3],[1,2]],dtype=float)

f = lambda inp: fvarf_sqrt_inv(inp,eps)
print("numerical\n",dnum(f,a))
print("analytical\n",dfvarf_sqrt_inv(a,eps))
print("*"*60)

f = lambda inp: gax(inp,eps)
print("numerical\n",dnum(f,a))
print("analytical\n",dgax(a,eps))


def 

In [ ]:
import numpy as np
from cs682.gradient_check import eval_numerical_gradient_array

def dnum(f,x):
    return eval_numerical_gradient_array(f,x,1,h=1e-6)

def asum(x):
    return np.sum(x,axis=0)*np.ones_like(x)

def dasum(x):
    return 1

def x_asum(x):
    return x*(asum(x))

def dx_asum(x):
    return asum(x)+x*dasum(x)


f = lambda inp: x_asum(inp)
print("numerical\n",dnum(f,a))
print("analytical\n",dx_asum(a))
print("*"*60)
