In [6]:
import numpy as np
a2d=np.arange(1,22,1).reshape(3,7)
print(a2d)
bl=a2d%3==0
print(bl)
print(bl[None,:,1].T*a2d)
print(np.sum(bl[0,:]))


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[False False  True False False  True False]
 [False  True False False  True False False]
 [ True False False  True False False  True]]
[[ 0  0  0  0  0  0  0]
 [ 8  9 10 11 12 13 14]
 [ 0  0  0  0  0  0  0]]
2
