In [18]:
import numpy as np
x=np.arange(0,6,1).reshape(2,3)
print(x)
np.add.at(x.T,[0,0,1],1)
print(x)
np.argmax(x,axis=1)
lrs = [1e-7, 5e-5,1e-4]
regs = [2.5e4, 5e4,500]
a=(regs[1]-regs[0]/regs[2])
b=((lrs[1]-lrs[0])/lrs[2])
print(a*b*1000)
lrs = [1e-7, 5e-5,1e-5]
regs = [0.25,1,0.25]
print(np.arange(1,2,1))
random_float_number = np.random.uniform(49.5, 99.5,size=100).tolist()
print(random_float_number)
for rg in np.arange(regs[0],regs[1],regs[2]).tolist():
    print(rg)


[[0 1 2]
 [3 4 5]]
[[2 2 2]
 [5 5 5]]
24925050.0
[1]
[72.10281895042161, 64.12954279897778, 88.01665621010444, 83.02344581618925, 85.3044790808915, 53.8957689647665, 70.06495104372921, 64.18351209054947, 79.79178977398894, 82.43822113109015, 68.0929340364919, 68.59193052396171, 56.041935936346945, 99.45261439251782, 78.46190403799172, 53.14636372392438, 58.738543864924935, 59.73670442031312, 80.70547767689239, 77.59345012015966, 85.87741003538046, 59.79393564974454, 94.27384255574803, 77.4088311119353, 77.71621643953594, 91.64509053298225, 75.9595984391892, 83.66775562474791, 68.57603510994429, 85.43790424759027, 73.92084478698928, 93.52569299393116, 97.06322465260976, 94.82463808809463, 53.294156948905595, 98.23172640305825, 75.4675072515968, 95.35368412483957, 62.17979944584863, 53.310165794469846, 75.37118618308072, 88.5039975349812, 69.3649065741545, 90.96183092061074, 64.40067358723385, 81.13666050520315, 59.3113374752903, 91.09738996011805, 70.52157966303153, 62.60596601901202, 5